version: '3'
services: 
  backend:
    build: 
      context: ./Backend/
    ports: 
      - '5000:5000'
    depends_on: 
      - 'database'

  frontend:
    build:
      context: ./Frontend/
    ports: 
      - '80:80'
    depends_on: 
      - 'backend'

  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 4tl4nt45
    ports:
      - "3307:3306"